---
unix_user: ianducrot

project_name: gitlab

# Passords
unix_password: "HelloThereGeneralKenobi"


home_ip: 79.95.197.59

gitlab_ip: 51.15.220.38

iptable_config_file: "inventories/nginx/templates/iptables.conf"